#! /bin/sh

# Ensure correct ownership and permissions on volumes
chown riak:riak /var/lib/riak /var/log/riak
chmod 755 /var/lib/riak /var/log/riak
# Ensure the desired Riak backend is set correctly
sed -i.bak "s/storage_backend = \(.*\)/storage_backend = ${DOCKER_RIAK_BACKEND}/" /etc/riak/riak.conf

riak start
stanchion start;
riak-cs start;
echo "wait 10 sec for services to start"
sleep 10

echo "generate key and secret"
R=$(curl -XPOST http://localhost:8080/riak-cs/user  -H 'Content-Type: application/json' -d '{"email":"admin@admin.com", "name":"admin"}')

key=$(echo $R | grep -Po '"key_id":"\K(.*?)(?=")')
secret=$(echo $R | grep -Po '"key_secret":"\K(.*?)(?=")')

credentialPath=/var/lib/riak/.credential
rm $credentialPath
touch $credentialPath
echo key: $key >> $credentialPath
echo secret: $secret >> $credentialPath 

echo "*** ***"
echo "key: $key"
echo "secret: $secret"
echo "*** ***"
echo "Saved in " $credentialPath

sed -i.bak "s/admin.key = admin-key/admin.key = $key/" /etc/riak-cs/riak-cs.conf
sed -i.bak "s/admin.secret = admin-secret/admin.key = $secret/" /etc/riak-cs/riak-cs.conf

sed -i.bak "s/admin.key = admin-key/admin.key = $key/" /etc/stanchion/stanchion.conf
sed -i.bak "s/admin.secret = admin-secret/admin.key = $secret/" /etc/stanchion/stanchion.conf

sed -i.bak "s/access_key =/access_key = $key/" /root/.s3cfg
sed -i.bak "s/secret_key =/secret_key = $secret/" /root/.s3cfg

CRED_PATH=/var/lib/riak/.credential

key=$(cat $CRED_PATH | grep -Po 'key: \K(.*)')
secret=$(cat $CRED_PATH | grep -Po 'secret: \K(.*)')

stanchion stop;
riak-cs stop;
riak stop